// api/generate.js
export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    const { prompt } = req.body;
    
    // Reads directly from Vercel Environment Variables
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
        return res.status(500).json({ error: 'API key is missing in Vercel environment variables.' });
    }

    try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
        
        const payload = {
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: "OBJECT",
                    properties: {
                        question: { type: "STRING" },
                        options: { type: "ARRAY", items: { type: "STRING" } },
                        answer: { type: "STRING" },
                        explanation: { type: "STRING" }
                    },
                    required: ["question", "options", "answer", "explanation"]
                }
            }
        };

        const response = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorData = await response.text();
            console.error("Upstream Gemini Error:", errorData);
            return res.status(response.status).json({ error: `AI connection failed with status: ${response.status}` });
        }

        const data = await response.json();
        
        // Extract raw JSON string generated by Gemini
        const rawContent = data.candidates[0].content.parts[0].text;
        
        // Parse it server-side to ensure integrity, then return to frontend
        const jsonResponse = JSON.parse(rawContent);

        return res.status(200).json(jsonResponse);

    } catch (error) {
        console.error("Internal Server Error:", error);
        return res.status(500).json({ error: 'Failed to process request.' });
    }
}
